spring:
  application:
    name: rsflood #todo: change
  datasource:
    url: jdbc:postgresql://localhost:5432/floods
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
